# IBM Developer's Workframe/2 Make File Creation run at 14:54:58 on 12/11/92

# Make File Creation run in directory:
#   D:\COLOS2\BASIC;

# Assumed INCLUDE environment variable path:
#   D:\COLOS2\BASIC;
#   D:\TOOLKT20\C\OS2H;
#   D:\TOOLKT20\ASM\OS2INC;
#   D:\IBMC\INCLUDE;


CNRBAS.RES:  CNRBAS.RC  \
#  {.;$(INCLUDE)}OS2.H  \
   {.;$(INCLUDE)}CNRBAS.H  \
   PERSON.ICO  \
   MAKEFILE

CNRBAS.OBJ:  CNRBAS.C  \
   MAKEFILE
