# make makefile
#
# Tools used:
#  Compile::Resource Compiler
#  Compile::GNU C
#  Make: make
all : cnrbas.exe

cnrbas.exe : cnrbas.obj cnrbas.res cnrbas.def
	gcc -Zomf cnrbas.obj cnrbas.def -o cnrbas.exe
	wrc cnrbas.res

cnrbas.obj : cnrbas.c cnrbas.h
	gcc -Wall -Zomf -c -O2 cnrbas.c -o cnrbas.obj

cnrbas.res : cnrbas.rc 
	wrc -r cnrbas.rc

clean :
	rm -rf *exe *res *obj *lib *dll *map
